### ISSUE TITLE
Template render error

### ISSUE THREAD

**Issue by mstoltenburg** [liveblog/liveblog-amp-theme#16]
I always get a Template render error at https://github.com/liveblog/liveblog-amp-theme/blob/a422ef0f9a0751d58a9fc225df327de981c9c340/templates/template-post.html#L56
If I change that line to `{% elif item.post_items_type | truncate(5, True, '', 0) == "embed" %}` it works fine.
```
gulp watch-static
[15:10:31] Using gulpfile ~/Sites/liveblog-amp-theme/gulpfile.js
[15:10:32] Starting 'clean-js'...
[15:10:32] Starting 'clean-css'...
[15:10:32] Finished 'clean-js' after 8.37 ms
[15:10:32] Starting 'browserify'...
[15:10:32] Finished 'clean-css' after 32 ms
[15:10:32] Starting 'less'...
[15:10:32] Finished 'browserify' after 386 ms
[15:10:32] Finished 'less' after 550 ms
[15:10:32] Starting 'index-inject'...
(node:61653) ExperimentalWarning: The http2 module is an experimental API.
[15:10:32] gulp-inject Nothing to inject into template-index.html.
/Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:501
                    if(err) { throw err; }
                              ^

Template render error: (unknown path)
  Template render error: (/Users/slomo/Sites/liveblog-amp-theme/templates/template-timeline.html)
  Template render error: (/Users/slomo/Sites/liveblog-amp-theme/templates/template-timeline-loop-content.html)
  Template render error: (/Users/slomo/Sites/liveblog-amp-theme/templates/template-post.html) [Line 56, Column 31]
  parseAggregate: expected comma after expression
    at Object.exports.prettifyError (/Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:489:31
    at eval (eval at _compile (/Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:26:11)
    at /Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:497:25
    at eval (eval at _compile (/Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:150:12)
    at /Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:497:25
    at eval (eval at _compile (/Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:568:24), <anonymous>:60:11)
    at /Users/slomo/Sites/liveblog-amp-theme/node_modules/nunjucks/src/environment.js:23:23
    at RawTask.call (/Users/slomo/Sites/liveblog-amp-theme/node_modules/asap/asap.js:40:19)
    at flush (/Users/slomo/Sites/liveblog-amp-theme/node_modules/asap/raw.js:50:29)
```

**Comment by nistormihai** [comment]
Hey Moritz  thanks for the catch, we will add this, but please fell free to make PR.

**Comment by tomaszrondio** [comment]
fixed
